version: "3.7"

services:
  mysql:
    build:
      context : .
      dockerfile: mysql.dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=geoquizz
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password