version: "3.7"
services:
  geoquizz-mysql:
    build:
      context : .
      dockerfile: mysql.dockerfile
    container_name: geoquizz-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=geoquizz
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./conf:/etc/mysql/conf.d/ 
  geoquizz-player:
    build:
      context: ./geoquizz-player
      dockerfile: player.dockerfile
    depends_on: 
      - geoquizz-mysql
    ports: 
      - "8080:8080"
    