version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=geoquizz
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - /data/mysql