version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=geoquizz
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - /data/mysql
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    build:
      context: ./geoquizz-player
      dockerfile: player.dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-app